{% set version = "0.8.1" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: fc733bf1ed5c1e286dddd182d37dabbdc1e01207dd15089f62be2021e29b0459

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - dask
    - future
    - numpy
    - xarray >=0.20.0

test:
  imports:
    - xgcm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
    - rabernat
