{% set version = "0.7.0" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: a40d015544cdeb909d229fdb759587afb583f2e8106cfa50d12811507f2f978d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools-scm
  run:
    - python >=3.9
    - dask
    - future
    - numpy
    - xarray >=0.20.0

test:
  imports:
    - xgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
    - rabernat
